name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**' # Chỉ kích hoạt khi thư mục backend có thay đổi

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cài đặt Pytest
        run: pip install pytest

      - name: Chạy Unit Test
        # Yêu cầu pytest quét thẳng vào file main.py để tìm bài test
        run: pytest backend/main.py