name: Project CI Pipeline

on:
  push:
    branches: [ "feature", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend # Trỏ mặc định vào thư mục backend
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Cài đặt thư viện Python
        run: pip install -r requirements.txt
      
      - name: Chạy Pytest
        run: pytest tests/ # Chỉ quét và chạy các file trong thư mục tests/

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Cài đặt thư viện Node (Jest & JSDOM)
        # Tích hợp lệnh cài đặt môi trường giả lập DOM như bạn vừa chạy local
        run: npm install jest jest-environment-jsdom --save-dev
        
      - name: Chạy Unit Test Frontend
        # Gọi trực tiếp jest với môi trường jsdom
        run: npx jest tests/ --env=jsdom